### ISSUE TITLE
How to use objects as cell values

### ISSUE THREAD

**Issue by teslor** [TonyGermaneri/canvas-datagrid#108]
Hi, I need some help related to the subject.
I have a data where some values are objects e.g. Col8: { a: 1, b: '3333', c: [1,2,3] } and I need to use such object as cell value.
1) How to use an object as a cell value without creating a new grid inside. I just need to keep object link and render manually, based on object properties.
2) In this case where to set actual text to show - in rendertext, rendercell or afterrendercell? Are there handlers I should prevent?
3) What if I need to show a text and some canvas drawings in the same cell (e.g. a button and a text near it)? I should draw everything manually (including text) in afterrendercell and prevent rendertext?
4) Can I use formatters when values are objects?
5) Where to set custom text for cell editing - beforebeginedit or beginedit?

**Comment by TonyGermaneri** [comment]
Thanks for posting this question.  It reveals a defect in the interface that I need to fix.  You cannot use formatters on values that are objects.

Right now, to determine if the cell is a grid or not this boolean is checked.

[isGrid = typeof d[header.name] === 'object' && d[header.name] !== null && d[header.name] !== undefined](https://github.com/TonyGermaneri/canvas-datagrid/blob/master/lib/draw.js#L486)

It should be altered to so that if a formatter is provided for the cell it should not be a cell grid.

I'll patch this up so using formatters will prevent it from drawing cell grids.

In the meantime, I believe you can hack it:

    var grid = canvasDatagrid();
    grid.formatters.widget = function (e) {
        return e.cell.value.a + ' ' + e.cell.value.b;
    };
    grid.schema = [
        {name: 'a'},
        {name: 'b'},
        {name: 'c'},
        {name: 'd', type: 'widget'}
    ];
    grid.addEventListener('beforerendercellgrid', function (e) {
        // super hack part.
        // Manipulate internal properties to make draw code paths think this isn't a grid
        e.cell.isGrid = false;
        e.ctx.fillRect(e.cell.x, e.cell.y, e.cell.width, e.cell.height);
        e.ctx.strokeRect(e.cell.x, e.cell.y, e.cell.width, e.cell.height);
        e.preventDefault();
    });
    grid.data = [{a: 'a', b: 'b', c: 'c', d: {a: '1234', b: 'nnnnn'}}];

Let me know if the hack works out.  I'll get it patched so formatters prevent cell grids from forming.

**Comment by teslor** [comment]
Thanks, I think this approach can help, I will check it for my data.
I also tried another workaround - passed an object as a string by using JSON.stringify, and used such code in string formatter:
```
var val = JSON.parse(e.cell.value)
return val.prop1 + ', ' +  val.prop2
```
It works fast enough, however I don't have access to object properties in event handlers in this case (I should parse it again or keep first parsed object somewhere), so the method you've offered looks better.

Could you also check questons 3 and 5, they are not directly related to the main question, but also important. For example I have such object as a cell value - { button: "Send", val: "3.14" }, I want to draw a cell like "[ Send ] Value: 3.14" where [ Send ] is a canvas rect (a button). I should draw everything in afterrendercell? Also I need when a user clicks on the text (I will determine it from coordinates) an input with "3.14" value would show (and ideally would not overlap a button). How to do it correctly and which handlers to use?

**Comment by TonyGermaneri** [comment]
Sorry for the very long delay in reply.

If you run this in a `DOMContentLoaded` event handler it should work and show a crude example of what I think you're talking about.  This example looks for a column called `A` and toggles the value to `X` or `O`.  

    'use strict';
    var x,
        y,
        data = [],
        grid = canvasDatagrid({
            parentNode: document.body
        });
    // make sure the grid does not get to big
    grid.style.height = '100%';
    grid.style.width = '100%';
    // make some fake data
    for (x = 0; x < 1000; x += 1) {
        data[x] = {};
        for (y = 0; y < 6; y += 1) {
            data[x][String.fromCharCode(65 + y)] = x * y;
        }
    }
    // set the fake data
    grid.data = data;
    // prevent the grid from drawing the text
    grid.addEventListener('rendertext', function (e) {
        if (e.cell.rowIndex > -1 && e.cell.header.name === 'A') {
            e.cell.formattedValue = '';
        }
    });
    // after the background of the cell is drawn, draw our "button"
    grid.addEventListener('afterrendercell', function (e) {
        if (e.cell.rowIndex > -1 && e.cell.header.name === 'A') {
            e.ctx.fillStyle = e.cell.value === 'X' ? 'green' : 'red';
            e.ctx.fillRect(e.cell.x + 5, e.cell.y + 5, 75, 25);
            e.ctx.fillText(e.cell.value, e.cell.x + 17, e.cell.y + 7);
        }
    });
    // listen for clicks and change the data value on click based on the data value of the cell
    grid.addEventListener('click', function (e) {
        if (e.cell.rowIndex > -1 && e.cell.header.name === 'A') {
            grid.data[e.cell.rowIndex].A = e.cell.value === 'X' ? 'O' : 'X';
        }
    });
    // stop the user from starting an edit input by double clicking
    grid.addEventListener('beforebeginedit', function (e) {
        if (e.cell.rowIndex > -1 && e.cell.header.name === 'A') {
            e.preventDefault();
        }
    });

If you want to get more accurate clicks you'll have to do as you suggested and listen for clicks and calculate the offsets from what you've drawn on the canvas.  `e` should contain all the information you need to determine what cell was clicked on and where to begin drawing from.

I know this isn't object tracking.  As we discussed earlier, I'll add the formatter function so using an object works as expected.  You can imagine what an object based version of this code would look like I think.  If not, I can provide another example once I have the formatter fix done.

Please let me know if you think there is an interface I can extend to help with the process.

> Where to set custom text for cell editing - beforebeginedit or beginedit?

You can do it anytime after the cell has began rendering.  As soon as `cell.value` is set you can alter that value.  That will change what appears in the input value.

So: `beforebeginedit`, `beginedit` (actually has `e.input`), `beforerendercell`, `rendercell`, `afterrendercell`, and `rendertext` are all valid events from which you can alter `e.cell.value` to get the edit input value to change when the user begins editing.

**Comment by teslor** [comment]
Thanks for the reply! I already did the most of needed things by myself by reading the documentation and experimenting :)
Your previous answeres helped a lot to do some things (especially using objects as values and preventing beforerendercellgrid).
I think it would be great to add the code from your answeres to the documentation.

I'm sure these features are important for the library:
1) Standard support for values as objects without hacks, since it's rather typical case.
2) Creating clickable elements in columns is also typical case. It would be good if the lib had standard functions to create such elements, at least buttons/checkboxes (e.g. maybe add formatters for button & checkbox) and handle clicks on them.
3) Optimization for FF/IE

**Comment by TonyGermaneri** [comment]
Thanks for all the input @teslor!  I agree with everything you've said there.  I am but one person though!  I would love some help doing that stuff.  Adding to the documentation is easy:

Words:

https://github.com/TonyGermaneri/canvas-datagrid/blob/master/tutorials/canvasDatagrid.md

Tutorials:

https://github.com/TonyGermaneri/canvas-datagrid/blob/master/tutorials/tutorials.js

> 1. Standard support for values as objects without hacks, since it's rather typical case.

Totally, this ticket is filed as a bug for that reason.  I think grid.formatters[type] is the best way to deal with it... or maybe make the cell grids non-default since they're kinda bizarre.

> 2. Creating clickable elements in columns is also typical case.

What if I took pictures of the checkbox the OS provides prior to drawing the grid, then displayed them when `column.type: checkbox` was detected.  I can coerce the value into bool and let clicks on the image coordinates alter the value.  There is already <select> if your column has the property `enum`, but it is supported in a different way.

> 3. Optimization for FF/IE

It'll happen.  The refactor between 19 -> 20 is a good reason why I don't do it now.  Rewriting complex stuff is made far more complex when you throw browser specific optimizations into the code.  Once it's a stable solid feature set with good (better?) code coverage I'll start optimizing the crap out of it, there's plenty of low hanging fruit.  My target is performance of around 100fps (<10ms).

**Comment by teslor** [comment]
I hope I will add something useful to the docs soon :)
Yes, I think cell grids shouldn't be a default behavior for objects. It's much more spesific case than using objecs as values.
