### ISSUE TITLE
scrollIntoView needs the capability to scroll to a given position in the view port.

### ISSUE THREAD

**Issue by sameeraroshan** [TonyGermaneri/canvas-datagrid#114]
scrollIntoView function with some kind of percentage parameter (eg 0.5 for middle.1 for end of the view-port. 0 for start of the view-port)

**Comment by TonyGermaneri** [comment]
I've added the additional arguments to the gotoCell function as you suggested.

https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid.gotoCell

The calculation is off by a few pixels due to another unrelated problem, but it's probably not noticeable unless you try to right or bottom justify the cell, then you'll see it clip the scroll bar.  I'm working to fix that issue in #97 which should fix this as well.  I'll leave this ticket open until it #97 is fixed and come back and QA this to make sure it indeed fixes the issue.

**Comment by sameeraroshan** [comment]
great tony. can you add that variables to scrollIntoView function too.

**Comment by TonyGermaneri** [comment]
Yeah, why not.

**Comment by TonyGermaneri** [comment]
I'm closing this issue, I'll reopen it again if #97 does not make it pixel perfect.
