### ISSUE TITLE
holding left mouse click on scroll bar and dragging mouse pointer away from table causes scroll bars to attach to scroll evnet even left mouse click is released.

### ISSUE THREAD

**Issue by sameeraroshan** [TonyGermaneri/canvas-datagrid#120]
#steps to create
1. click and hold left mouse button on scroll bar( horizontal or vertical) 
2. drag mouse pointer away from the window (to address bar of the browser)
3. release the left mouse button there on the address bar.
4. drag mouse pointer to table again.
5. scroll bar still responds as left mouse button is clicked. but ideally it should not respond to mouse movements because no mouse button is clicked on the scroll bar.

**Comment by TonyGermaneri** [comment]
You can change this behavior with the [scrollPointerLock](https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid.args.scrollPointerLock) attribute.

The reason it behaves this way is due to the browser preventing any events outside of the HTML document from firing, so as soon as that mouse leaves the window, I can't detect it anymore.  So mouse up events are not seen either.   There is no fix for this because the behavior is intended by the W3C, but there is a workaround.  W3C introduced pointer lock mode which causes the mouse cursor to disappear and return deltas for movement until the cursor is released.  Because it causes the cursor to vanish I have it set as not the default, but I recognize the problem so offer at least some alternative.

**Comment by sameeraroshan** [comment]
tony this can be fixed using  ` document.addEventListener('mouseout',self.stopScrollGrid, false);`
inside `mousedown` function
```
document.body.addEventListener('mousemove', self.scrollGrid, false);
document.addEventListener('mouseout',self.stopScrollGrid, false);
document.body.addEventListener('mouseup', self.stopScrollGrid, false);
```
it solved the above issue. you can do this to column drag, resize , etc

**Comment by TonyGermaneri** [comment]
That's great!! That was SOO annoying.  Is there any way you can make a PR to fix it?

**Comment by TonyGermaneri** [comment]
Thanks again for figuring out a better work around for this issue.
