### ISSUE TITLE
Error in the example reactExample.html

### ISSUE THREAD

**Issue by SerZubkov** [TonyGermaneri/canvas-datagrid#136]
### Expected behavior and actual behavior.
Hi!
Bug in the browser Safari: `NotSupportedError: A newly constructed custom element must not have child nodes`

### Steps to reproduce the problem.
- Open link (https://tonygermaneri.github.io/canvas-datagrid/tutorials/reactExample.html) in browser Safari 11.1.1 (13605.2.8)

### Specifications like the version of the project, operating system, or hardware.
macOs High Sierra 10.13.5, Safari 11.1.1 (13605.2.8),

**Comment by TonyGermaneri** [comment]
Very strange.  I'm familiar with the error, I don't think I'm adding child nodes to the custom element, strange that chrome doesn't complain about it.  I'll try and figure out what it's complaining about, thanks for the report!

**Comment by NeoWorkPage** [comment]
and in FireFox (61.0.1) same problem =(

**Comment by TonyGermaneri** [comment]
The component I wrote to wrap the grid component is what's throwing the error, not the grid itself, which should work just fine in react if a proper wrapper is used.  I'll try and fix this bug in the next day or two.  If you can see what is wrong before hand make a PR or let me know here, it'd help a lot.

This is the file: https://github.com/TonyGermaneri/canvas-datagrid/blob/master/tutorials/reactExample.js

I almost looked at it.  The error speak of attaching divs at the wrong time (the wrong method).

**Comment by betososa** [comment]
Hello! I tried to debug this ticket, but i think is a little more complex than what I though not very brilliant :(
I think the error has something to do with the `canvas-datagrid` webcomponent.
The same `NotSupportedError: A newly constructed custom element must not have child nodes` error is thrown by safari when opening the [webcomponentDemo](https://tonygermaneri.github.io/canvas-datagrid/tutorials/webcomponentDemo.html)

Only the data is shown
![image](https://user-images.githubusercontent.com/1018478/43877701-f6008be2-9b60-11e8-9945-0129a006e753.png)

* Same for Firefox Version 61.0.1 (64-bit) & Safari Version 11.0 (12604.1.38.1.7)

**Comment by TonyGermaneri** [comment]
@betososa!  Hello!  Hope you have been well.

Good to know about the webcompoent demo not working too, that will rule out any possible problem with the react demo.

`A newly constructed custom element must not have child nodes` I've seen this in the past with chrome when I was first creating the web component constructor, like the error suggests, it does not like having child nodes added to the element (in this case the <canvas-datagrid> tag).  There is an exception made for shadow dom nodes, so perhaps there is no such exception or the shadow dom node is treated differently in these other browsers.

I've been super busy at work but I promise I'll look into this very soon unless @betososa fixes it first.

Here is some insight:

This is where the grid is actually registered as an element and attached to the native DOM:

https://github.com/TonyGermaneri/canvas-datagrid/blob/master/lib/main.js#L62


This is where the script goes from normal JS script to ES6 web component.  The reason the code is wrapped in an eval is to allow it to be interpreted by ES5 browsers without throwing syntax errors as it is new ES6 syntax:

https://github.com/TonyGermaneri/canvas-datagrid/blob/master/lib/main.js#L25


Just a little further down is where the shadow dom is added.  Since it's complaining about DOM elements being added too early, maybe this is the one?  But I think the specs (and certainly chrome) allows a single shadow dom element to be added prior to component connect event:

https://github.com/TonyGermaneri/canvas-datagrid/blob/master/lib/main.js#L44


This is where the grid runs the "it's ok to add child elements now" part.  if the shadow dom is really what is causing the issue, you can move the creation of the element to this function so it shows up at the right time in the life cycle:

https://github.com/TonyGermaneri/canvas-datagrid/blob/master/lib/component.js#L106

**Comment by BelonaIJG** [comment]
Hi Tony,
I'm giving a check on your component and i noticed that the react example still not working in **FF 65.0.2**.

The error in FF is: **"NotSupportedError: Operation is not supported"**
A little bit different from the Safari msg.

Have you planned to resolve this incompatibility?

Thanks in advanced .

**Comment by TonyGermaneri** [comment]
Yes, I plan on fixing it.  I haven't made any updates to the project in several weeks because I'm stuck in a all engrossing work project.  The bug is not impossible to fix.  It has to do with the order in which things are loaded.  I apparently was not careful enough in some code paths to not contaminate the web component element with attributes prior to mounting it.  Basically a race condition.  Sorry for the very long delay.  I can point you in the right direction if you're interested in trying to fix it yourself.
