### ISSUE TITLE
Is it possible to have a frozen footer

### ISSUE THREAD

**Issue by rdavi10471a2** [TonyGermaneri/canvas-datagrid#137]
### Expected behavior and actual behavior.
looking for a way to have a total row total row that allows the body to scroll? if not how hard would it be to wire into the scroll event to fetch the viewable columns and render then to a secondary div under the grid

**Comment by TonyGermaneri** [comment]
I imagine a single row footer wouldn't be a terrible feature.  It won't get done anytime soon, there's mountains of work before it, but I'll add it to the to-do list.  The second idea you had is very easy to do:

```
window.addEventListener('load', function () {
    var parentNode = document.body;
    var footer = document.createElement('div');
    var grid = canvasDatagrid({
        parentNode: parentNode
    });
    function updateFooter() {
        footer.innerHTML = 
        	'Col 2 Max: <b>' +
        	Math.max.apply(null, grid.data.map(function (row) { return row.col2; }))
          + '</b> Col 2 Avg: <b>' +
          (grid.data.map(function (row) { return row.col2; }).reduce(function (a, v) { return a + v; }, 0) / grid.data.length) + '</b>';
    }
    grid.addEventListener('datachanged', updateFooter);
    setInterval(function () {
      grid.data = [
        {col1: 'foo', col2: Math.random(), col3: 'a'},
        {col1: 'bar', col2: Math.random(), col3: 'b'},
        {col1: 'baz', col2: Math.random(), col3: 'c'}
      ];
    }, 100);
    parentNode.appendChild(footer);
});```

Note that the event `datachanged` will not fire when the data object is directly manipulated.  You'll have to run the `updateFooter` function yourself if you manipulate the data that way.  You'll also need to call `grid.draw` as well.  The reason is the grid cannot listen for changes to the elements of the array, just the setter `grid.data`.

**Comment by rdavi10471a2** [comment]
make that
http://jsfiddle.net/qr1cythe/18/

and your example as well
http://jsfiddle.net/25ngbszd/12/

**Comment by TonyGermaneri** [comment]
Nice work!  I never thought I'd see a virtual scroll bar controlling a real scroll bar, but... there it is.  If you want it to fire more frequently remove the debounce code, that's there to prevent over-use of XHR resources.  Since you're just updating a DIV you can fire it off as frequently as you like.

**Comment by rdavi10471a2** [comment]
Thanks.
Insomnia is great epiphany time -- use  a grid with the headers turned off
as the footer and syncronize those scrolls.. problem is you need to be able
to hide one grids scroll so it can control the other.... reading docs.
Thinking in the 33rd dimension.

RD

**Comment by TonyGermaneri** [comment]
There is no way to turn it off, but you can alter the dimensions so the height or width is 0 which should effectively turn it off.  I'm like 72% sure it will work like that.

**Comment by rdavi10471a2** [comment]
appears to turn them both off I only want to turn off the horizontal
scrollbar.
Ideas?

**Comment by rdavi10471a2** [comment]
This works !! and is exactly what I was pondering last night.
Except that  the vertical scroll is turned off as well?

http://jsfiddle.net/qr1cythe/43/


RD

**Comment by TonyGermaneri** [comment]
I know it's been a while, but is your issue resolved?   If not please open the issue again.  FYI I've added `overflowX` and `overflowY` since we had this conversation.  Seems related.
