### ISSUE TITLE
Black screen occurs when excel size is large

### ISSUE THREAD

**Issue by Navya-adft** [TonyGermaneri/canvas-datagrid#161]
i am using canvas-datagrid with sheet.js to import excel file in my project..It work fine when the excel file is small , but i import excel file with more than 2000 rows and columns (around 432 KB size) it shows black screen
Its only happens in Chrome

**Comment by TonyGermaneri** [comment]
Should work just fine, that's a tiny number of records, I've tested it with >100M rows, so the size is probably not the issue.  Do you have any error messages in the console?  Have you constrained the size of the grid so it doesn't attempt to draw off screen (e.g.: `grid.style.height = "100%";grid.style.width = "100%";`).

What you're doing should totally work.

**Comment by Navya-adft** [comment]
i testes with 2000 rows ,no error in the console only black screen and also ,i got the rows values in the console . the problem is only in chrome.

![image](https://user-images.githubusercontent.com/32817841/44242317-93014f80-a1fb-11e8-9045-cde5dde94ae6.png)
i got this error at all time, but i think it is not affect to the size of the grid..

**Comment by TonyGermaneri** [comment]
This is great info, this tells you exactly what the problem is, and it's not related to the canvas-datagrid program.  This is also an easy error to fix.  Your browser is upset that your web server is sending the wrong MIME type in the response.  The "correct" MIME type for a JS file is `text/javascript`.  That's what the server should send, the actual correct one is `application/javascript` which old IE barfs at.

Look up the documentation of your HTTP server to see why it's not sending the proper MIME type and how to fix it.  If you tell me what sort of HTTP server you're using I might be able to help if I've used it before.
