### ISSUE TITLE
Modify input box functionality

### ISSUE THREAD

**Issue by kkuang70** [TonyGermaneri/canvas-datagrid#168]
Is there a way to modify the functionality of the input box? I am trying to implement auto-complete for input boxes for certain cells.

**Comment by TonyGermaneri** [comment]
Check out the [`appendedinput`](https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid#event:appendeditinput) event.   It allows you to intercept the input getting added to the grid.  You can then manipulate it, attach events to it, prevent it from being appended to an element, move it around, etc..

You can also generally change it from an input to a textarea by setting the [`multiLine`](https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid.args.multiLine) attribute to true.

Also, you can have [selects instead of inputs.](https://tonygermaneri.github.io/canvas-datagrid/docs/#tutorial--Use-select-instead-of-input-for-edits).

There is an autocomplete function [here](https://github.com/TonyGermaneri/canvas-datagrid/blob/master/lib/contextMenu.js#L302) if you want inspiration.  Probably not the best autocomplete code in the world, but it does use the grid data, so that might be helpful.

Open this issue back up if you need additional functionality or event hooks here.
