### ISSUE TITLE
"Hide rowHeaderCell" elicits "Uncaught TypeError: Cannot set property 'hidden' of undefined"

### ISSUE THREAD

**Issue by SheetJSDev** [TonyGermaneri/canvas-datagrid#176]
See https://github.com/SheetJS/js-xlsx/issues/1326 for repro and error message

**Comment by TonyGermaneri** [comment]
Thanks for the heads up, I'll get it fixed ASAP.

**Comment by TonyGermaneri** [comment]
I removed the option from the context menu.  It is not designed to be a setting the end user can turn on and off because it's not a column of data and there is no control around granting the ability to toggle it as there is for data and turning the row headers on and off.  If the ability to turn the row headers on and off by context menu it is trivial to add it back to the context menu.  I can post sample code if anyone is interested in how to allow the user to hide the row headers for their implementation.
