### ISSUE TITLE
HI, I want to delete some row but I can't

### ISSUE THREAD

**Issue by z2131023** [TonyGermaneri/canvas-datagrid#179]
![image](https://user-images.githubusercontent.com/22854141/47900397-bdd47900-deb7-11e8-9fe2-2148c63f1b41.png)

HI ! 
I want to delete the selected row ,  what should I do ,    Can I find some methods in API?
Many thanks

**Comment by z2131023** [comment]
![image](https://user-images.githubusercontent.com/22854141/47900883-69ca9400-deb9-11e8-9920-3283eab40489.png)
and this. delete select items , what should i do, only items

**Comment by TonyGermaneri** [comment]
I always rely on deleting the data manually.  To actually delete data you just remove it from the `grid.data`.  E.g.: `grid.data.splice(0, 1);` will remove row index 0.  Since the grid can't tell that you've manipulated the data object it may be necessary to call `grid.draw();` to update the drawing on the canvas.  For the second question, I imagine you want to delete the data in the cells you've selected when the user presses a key.  So bind an event listener to the key event `grid.addEventListener('keyup', function (e) { ... });`

In here you'll check what key was pressed by looking at `e.keycode`.  Check MDN for a more thorough explanation on listening for keystrokes (google "MDN keyup").

Once you detect the key you want to listen for (probably delete?) then you can remove the data from the selected matrix of data.  You can see the matrix by looking at [grid.selections](https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid.selections) and iterate though the data removing the data from the cells you want empty.

```
grid.addEventListener('keyup', function (e) {
    if (e.keycode === 53) {
        grid.selections.forEach(function (selectedCells, rowIndex) {
            selectedCells.forEach(function (cellData, cellIndex){
                grid.data[rowIndex][cellIndex] = '';
            });
        })
    }
});
```

I did not test this, I don't know if it will work, but it will be something like this.  I don't know what keycode 53 is, you'll have to look up the keycode for the key you want to use.

You can also use the context menu built into the grid to add a delete option:

https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid#event:contextmenu

Same code, just without the keycode handler stuff.

**Comment by TonyGermaneri** [comment]
If you have more questions on how to implement the grid you can join the slack channel by sending me your email.

**Comment by z2131023** [comment]
many thaks
