### ISSUE TITLE
Few questions about inject custom areas to grid and writing custom editor for cells.

### ISSUE THREAD

**Issue by Daeamon** [TonyGermaneri/canvas-datagrid#183]
Hello, i have few questions.
1) How to add custom area between grid header and grid body?
2) How to add custom area into cell header?
3) How to write my custom editor?
If i think correctly, i need to rewrite canvas datagrid component myself for this features?

**Comment by TonyGermaneri** [comment]
You can do any of the above using event handlers and style manipulation.  Each cell is an "entity", this is the unit used for mouse collision detection (is your mouse over something), so what your asking is possible without a new lib.

That said, because the behavior is different than the default you'll have to write the rendering code for the custom areas you're talking about, and perhaps "fix" some of the side effects of the custom implementation (e.g.: You might have to draw your own column titles).

For 1 and 2:

1) change the style of the element I want to replace.  In this case set `columnHeaderCellHeight` to the desired target height.
2) [Attach to a few events and replace the cell with a new image/HTML](https://tonygermaneri.github.io/canvas-datagrid/docs/#tutorial--Draw-a-picture)
3) [Attach to some more events to detect clicks for new functionality you like.](https://tonygermaneri.github.io/canvas-datagrid/docs/#tutorial--Detect-clicks)

For 3:
1) Attach to [beginedit](https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid#event:beginedit), you can then manipulate `e.input` to your heart's content.  If you want to replace it entirely, just hide it and attach events to your new editor to update the hidden input when your data changes.  When you're done call `grid.endEdit()` to stop the editor.  There's probably some more to do around validation, but you'll have to handle that in your editor.  To position the editor, you'll have to absolutely position it, to find the right location use `e.cell.x` or `e.cell.offsetTop` etc. to determine where it should go.  The same is done for the input, so you might just be able to copy the `top` and `left` properties from it and use it in your editor.

I'm curious if you intend on continuing, and if you do how it comes out.

Good luck!  I hope you find the most profitable way forward.
