### ISSUE TITLE
selectionFollowsActiveCell not reseting selectionBounds on keydown

### ISSUE THREAD

**Issue by cthurston** [TonyGermaneri/canvas-datagrid#184]
### Expected behavior and actual behavior.
SelectionBounds to be in sync with selections on key navigation.

### Steps to reproduce the problem.
selectionFollowsActiveCell = true

Shift select a few cells with keyboard navigation.  Then just use the keyboard to navigate without shift or ctrl and the selectionBounds will be the previous selection.

**Comment by cthurston** [comment]
Looking through the keydown event, I think the fix is as simple as changing:
````
ev = {
   selectedData: self.getSelectedData(),
   selections: self.selections,
   selectionBounds: self.getSelectionBounds()  // was self.selectionBounds
};
````

**Comment by TonyGermaneri** [comment]
I see, so the event is showing a function instead of the selection bounds?  While this is getting fixed and deployed you can get at the same, and hopefully correct data using `grid.selectionBounds`.

If you are sure that fixes the problem, feel free to make a PR.  I'll fix it myself in short order if you're not feeling like it.

And thanks for finding the bug!

**Comment by ndrsn** [comment]
Seems to be working.
