### ISSUE TITLE
Plans for native Vue style and compatibility with vuetify?

### ISSUE THREAD

**Issue by SGarno** [TonyGermaneri/canvas-datagrid#188]
### Expected behavior and actual behavior.
The canvas-datagrid component looks very promising and powerful and very much needed in the Vue community.      Is there a version planned that is closer to how native vue components operate?   It would also be specially helpful if it was compatible with Vuetify and Nuxtjs.

### Steps to reproduce the problem.
n/a

### Specifications like the version of the project, operating system, or hardware.
n/a/

**Comment by TonyGermaneri** [comment]
Hi @BlackConure, I use it with Vuetify right now without any problem.  What sort of changes specifically are you suggesting?  I'm open to just about anything.  A Vue version?  Style mappings? I think we could probably do multiple build targets in webpack, e.g.: 1) WebComponent 2) Vue 3) React etc..  It wouldn't be hard.  The react example (that does not work in safari for some reason) shows a lightweight wrapper for react, but I don't use react, so it's nothing more than a POC.

If you're interested in making some PRs let me know.  Also, I have a slack channel, you can ask me about the stranger parts of the lib.

**Comment by TonyGermaneri** [comment]
> Don't take this the wrong way...
> How to define the template for the rows/headers.

I welcome any criticism.  All the more so if you're actually using the lib.

https://github.com/TonyGermaneri/canvas-datagrid/issues/142 should handle most, if not all, of the styling problems you pointed out.  It will allow you to specify per column styling using CSS classes.  Right now it's not very good at per column styles, most everything requires attaching to event handlers.  My plan is to have full CSS support, these event handlers are just lower level interfaces that allow you to do some things using imperative code now instead of waiting.


> How do you get CDG to respect the boundaries of the parent container
> How to make it responsive.


Try setting the height and width to 100%.

You need to tell it when to resize because resizing will require redrawing the canvas, not just resizing the canvas element, and believe me, you do _not_ want to see the grid resized without redrawing.  I attempt to do this automatically by using a series of mutation observers, getters/setters and event handlers - which totally don't work all the time.  The grid can tell when the entire window gets resized and respond to that, but when other elements get resized, you might need to give the grid a hint that it's time to resize (run `grid.resize()`).  Adding inline styles, imperative code commands (e.g.: `grid.style.width = '100%`;`), or, if you're using the WebComponent version, a CSS class should be enough to get the style directive to the grid.  There is a bug in some browsers where if you're using imperative styles you need to set the height/width _after_ the grid is added to the DOM, there's a ticket open to fix it, has to do with feature detection gone wrong.

> Here is an example of a tree and a data grid that I am trying to create in Vuetify.

You can make that with CDG, but it's going to require you type a bunch of JS event handlers.  The main problem is what you already pointed out: there is no way to make buttons, checkboxes etc.  There is a good reason for that.  I don't think I can accommodate the various opinions of how a button should look.  So there are two way to get controls: 1) use schema data type `html` and allow the grid to draw HTML pictures into your grid cells (http://jsfiddle.net/5uw8z0pj/1/) 2) draw your own buttons using JS (canvas or image).  Both work well and are transparent to the user.  

*Both are images*, as you know the canvas itself is an image, so you need to react to the clicks of the images you have drawn, either by saying "a click anywhere on the cell is a click on the button" or doing actual mouse offset position detection, which is not super fun.  If you use "click anywhere on the cell..." it's actually fairly easy as the grid lib does the heavy lifting, you just attach to the cell click event.  The other method, you attach to ... more events, mouse move events, you have to know the size of the button, which again is an image, so I hope you measured it before.

If you can think of an interface that could provide this functionality without the events, let me know, it's a hard one that has come up more than once.

**Comment by BlackConure** [comment]
It is indeed tricky and why many people I have encountered just end up writing something custom every time.   I think your grid has a great deal of power and I love the fact that it has no dependencies.    I have done other apps in the past that are more spreadsheet like grids and I think canvas-datagrid would have been a slam dunk.    My current project, however, is different.   It needs the canvas part of what you have done, but all the other stuff is above and beyond my current needs (at the moment!).
