### ISSUE TITLE
Editing cells backed by objects

### ISSUE THREAD

**Issue by rowanhill** [TonyGermaneri/canvas-datagrid#196]
Hi,

I'm interested in using canvas-datagrid to display a moderately sized (~125 x 125) grid of objects with a small amount of visual formatting. Essentially, I have objects with properties that govern a) the text I want to display and b) the style of the cell (things like background colour / gradients). I want to be able to modify these objects based on text entered by the user.

I just wanted to check the most sensible way of achieving that. So far I've found that:
- I can use formatters to display the text I want in the grid
- I'm _expecting_ (but haven't tested) to be able to hook into the rendercell event and use e.ctx to draw pretty much whatever background I'd like on the cell, based on e.cell.value
- For editting, I need to a) hook into beginedit and override e.input.value with a sensible text value, and b) hook into beforeendedit to manually update e.cell.value _and_ call e.abort() to prevent canvas-datagrid overwriting cell.value with whatever plain text was entered. I guess this is also where I'll want to write back to a server, and then update the data array (which I guess won't have been updated since I aborted?)

Does that sound right? It feels a bit odd to abort the edit, but I've not been able to find any value on the event (or similar events) that allows me to manipulate what canvas-datagrid writes back. I'm also concerned that manually updating the data array will cause the grid to needlessly re-render, which might be a performance concern?

Thanks,
Rowan

**Comment by TonyGermaneri** [comment]
That's pretty much exactly what you would need to do.

> I can use formatters to display the text I want in the grid

Yes, you can do anything as long as it's not async, it must return a value.

> I'm expecting (but haven't tested) to be able to hook into the rendercell event and use e.ctx to draw pretty much whatever background I'd like on the cell, based on e.cell.value

You're a pro at this.  There are a bunch of cell rendering events `beforerendercell`, `afterrendercell`, `rendercell`, `formattext`, just to name a few.  Play with drawing on the canvas at different points in the draw cycle to see what might overlap your drawing.  E.g.: maybe you want the text to overlap your background, or maybe you have a new cell image altogether (e.g.: https://tonygermaneri.github.io/canvas-datagrid/tutorials/sparklineDemo.html).  You can do it async if you need to.  (E.g.: you need to resolve via a server request some data.)  If you need to do it async, be aware that the cell might have moved, you'll need to requery the cell's location with `visibleCells` (https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid.visibleCells)

You can use `e.cell.x` and `e.cell.y` to figure out exactly where the cell starts.  `e.cell.height` and `e.cell.width` are there too.

> For editting, I need to a) hook into beginedit and override e.input.value with a sensible text value, and b) hook into beforeendedit to manually update e.cell.value and call e.abort() to prevent canvas-datagrid overwriting cell.value with whatever plain text was entered. I guess this is also where I'll want to write back to a server, and then update the data array (which I guess won't have been updated since I aborted?)

Right, if you abort, the data won't be updated.  You can update it immediately or async without any issue since you know the location of the data.

Just to be clear, that's not a typical usage.  You're going to throw away the data the user entered (or at least send it off to the cloud) and you're going to replace it with the result of that request.  I'm sure you have a good reason for doing that, but just making sure I understand what you're doing.

Sounds like fun!  I'm sure your client will be impressed with what you're making.
