### ISSUE TITLE
Event-listeners garbage collection not happening

### ISSUE THREAD

**Issue by vermadev95** [TonyGermaneri/canvas-datagrid#244]
@TonyGermaneri @jswolf19 
### Expected behavior and actual behavior.
A single event listener function should be getting called only once but here when I did subscribe to event listener, the listener function is getting called total no of times the context menu is getting opened.

### Steps to reproduce the problem.
Subscribe to event listener of context menu and observe.

     
      let search = document.createElement('input');
      search.title = 'Search';
      search.id = "searchLogs"
      search.classList.add('form-control');
      content.appendChild(search);
      this.grid.addEventListener('contextmenu', (e)=> {
        search.addEventListener('keyup', this.filterEvent(search),true);
      });
      e.items.unshift({
        title: content
      });
      this.grid.addEventListener('datachanged',()=>{
      this.grid.removeEventListener('contextmenu',()=>{
      });
    });

I wrote the above code but unable to unsubscribe from the event listener of the searchbox appended in the context menu. And because of that event listener function is called multiple times.

**Comment by jswolf19** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener

If you want to remove an event listener, then you need to keep a handle to the function you add with `addEventListener`.

**Comment by TonyGermaneri** [comment]
That's all sorts of wrong.

This:

```
this.grid.addEventListener('contextmenu', (e)=> {
    search.addEventListener('keyup', this.filterEvent(search),true);
});
```

Should probably be this:

```
const searchEvent = this.filterEvent(search);
search.addEventListener('keyup', searchEvent, true);
```

You don't want to bind to an event more than once.  When it's time to remove the event, you would do this:

```
search.removeEventListener('keyup', searchEvent, true);
```

Same with `this.grid.addEventListener('datachanged',()=>{`.  

What your code is doing is saying "Each time the data changes, add another context menu listener".  If the data changes 10 times, that means you'll have 10 listener events (the context menu will run your function 10x when it opens).  This is for sure not what you're trying to do.

Try not to add event listeners inside of other events, it makes it very complex.  If must do that, and often you do, make sure each event you add, you also remove when the event is done.  That second part, removing the event, is what makes it complex.  You can avoid that complexity by not putting addEventListener within other addEventListener functions in the first place.

It's hard to say exactly what you should be doing because I'm not sure what you're trying to do.  @jswolf19  has the right idea, read on MDN about it, practice with simpler examples, then move to the more complex.   

If you give more context, I can maybe help you more.

Cheers,
Tony

**Comment by vermadev95** [comment]
@TonyGermaneri @jswolf19  Thanks for the reply. As you said I was implementing it wrongly earlier. I have made necessary corrections to it and its working fine now.
