### ISSUE TITLE
Icon Support

### ISSUE THREAD

**Issue by Kumar-Kishan** [TonyGermaneri/canvas-datagrid#267]
More of a question than a bug:
I need to draw font-awesome icons or  any icons, using the html type column type.
So, can you please guide me to a way so i could inject the font-awesome styles into html type columns

**Comment by TonyGermaneri** [comment]
That is probably going to be very difficult or impossible.  If you had the images of the icons it would be easy, but because icons are typically embedded in a font, it can be hard to get them working.  It is possible to render HTML onto the grid in a limited way, but it will not support all CSS (See the tutorial on rendering HTML in the docs), and loading fonts is likely going to be difficult or impossible.  If you find a way to get access to the icons outside of the font then you might have a chance, otherwise, it's something I haven't been able to do after about 1hr of working on it.  Might be possible.  If you do figure out how to do it, please do let me know, I would be very interested.

**Comment by Kumar-Kishan** [comment]
Thanks, for the speedy response. I will try to find a way if possible.
