### ISSUE TITLE
Isolated Instances

### ISSUE THREAD

**Issue by josh-hemphill** [TonyGermaneri/canvas-datagrid#316]
Is there any way to isolate the instance of canvas-datagrid?
In large apps, each section needs to be able to load and unload its dependencies since other portions of the app often have no need for most of them.
Having some way to keep it out of global scope would be helpful.

**Comment by TonyGermaneri** [comment]
There is no way to prevent it from adding a constructor ref to the window object.  That said, it is a reference to the constructor, not an instance.

I agree it is bad form to pollute the global scope, but it was the style back then.  In order to maintain backwards compatibility another build needs to be made.  Thanks to @ndrsn we have a very nice CI/CD that can be altered to produce such builds.

Multiple builds have not yet been setup, but it would be a very nice thing to have.  I think what you want would be called the "module" build and would export itself as an ES6 module and omit any code that touches window or other legacy/antiquated APIs.
