### ISSUE TITLE
Touch Events are missing "cell" property

### ISSUE THREAD

**Issue by luveti** [TonyGermaneri/canvas-datagrid#63]
The touch events seem to be missing the "cell" property, even though the docs say they should have it.

![image](https://user-images.githubusercontent.com/4952718/32810963-66c82dda-c96b-11e7-980c-26c5f8e5923a.png)

![image](https://user-images.githubusercontent.com/4952718/32810970-6b3c7812-c96b-11e7-9482-a9a6a0f4433b.png)

![image](https://user-images.githubusercontent.com/4952718/32810974-702fd7d8-c96b-11e7-9be3-935fb4fac9d5.png)

The cell that it finds via getCellAt isn't found until way after the event has been dispatched.

![image](https://user-images.githubusercontent.com/4952718/32811059-cb275ac6-c96b-11e7-8162-1b5736548e78.png)

**Comment by TonyGermaneri** [comment]
Thanks for finding this bug, I'll fix it right away.

**Comment by TonyGermaneri** [comment]
I pushed a fix in v0.18.13, but I think I introduced a new bug that will crash the program.  ugh...  just a minute.

**Comment by TonyGermaneri** [comment]
Ok, v0.18.14 is way less crashy.  Thanks again for finding the bug!

**Comment by luveti** [comment]
Sweet :D thank you for your hard work on this library! :)

**Comment by luveti** [comment]
It looks like you've removed the cell property from the other three touch events. Does adding those require a lot of work? My goal is to handle touchstart, touchmove, and touchend with my mousedown, mousemove, and mouseup event handlers. My mouseup event is currently using the cell position to determine if the user pressed a specific region of a cell.

**Comment by TonyGermaneri** [comment]
It isn't difficult to add them.  They were left out as a product of premature optimization.  It's a disease as a programmer I've come to accept I suffer from.  I was laboring under the false impression the event handler code was slowing down my animations.  I'll update the library to include cell in the three touch events you mentioned.

In the meantime you can determine the cell by manually calling [getCellAt](https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid.getCellAt) and passing the x, y coordinates to it.  As long as you don't need to use any sort of inner grids (cell or tree grids) the calculations are very straight forward.  Something like `grid.getCellAt(e.NativeEvent.layerX, e.NativeEvent.layerY);` should return the cell on a click.  Touch is more complex, it has an array of fingers.  Inner grids are more complex because they have to walk the virtual ancestor offset to the top of the canvas.

**Comment by TonyGermaneri** [comment]
I've added the event `beforetouchmove` which is the old `touchmove` event.  So to cancel a `touchmove` you can still use `beforetouchmove`.  `touchmove` now occurs a bit later after the current cell has been calculated.  Reopen the issue if you find you are still missing event data.
