### ISSUE TITLE
Demo of grouped column and row headers with in datagrid

### ISSUE THREAD

**Issue by vasu-vvp** [TonyGermaneri/canvas-datagrid#64]
Is it possible to create following type of grid format using canvas-datagrid. Can you please provide any demo example for the same. Please refer attachment. 

![image](https://user-images.githubusercontent.com/30551082/33169357-66abaf42-d06a-11e7-9d2f-980ce72e970d.png)

Thanks!

**Comment by TonyGermaneri** [comment]
There is presently no way to span/merge cells/rows and I don't really see that happening before V1 due to the profound change that would have on core functionality.

That being said, you can make it appear that way using _heavy_ use of render and mouse/touch event listeners as well as row and column freeze functionality.  

1. Shut off the "real" headers by setting the attributes (not properties) (showRowHeaders)[https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid.args.showRowHeaders] and (showColumnHeaders)[https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid.args.showColumnHeaders] to false.  

2.  Subscribe to the events [afterrendercell](https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid#event:afterrendercell) where you can alter both canvas draw styles such as [cellBackgroundColor](https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid.style.cellBackgroundColor) and [cellBorderColor](https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid.style.cellBorderColor) to supress and change basic colors of each "header" cell.  Then within the same event (`afterrendercell`) you can draw your own text into the now "blank" cells, which are not spanned, but have no borders so they appear to be spanned.

3. The behaviors of the "new" row headers can be altered usingthe events [touchstart](https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid#event:touchstart) and [click](https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid#event:click).  Re-implementing the default behaviors of the row headers is not difficult, but any attempt to sort the data using built in sorters will result in a mucking up of your headers, so you will have to implement your own [sorting methods](https://tonygermaneri.github.io/canvas-datagrid/docs/#sorters) and attach them to any data types you plan on sorting (number? string? other?).  Same goes for [filters](https://tonygermaneri.github.io/canvas-datagrid/docs/#filters).

4. To prevent the rows and columns in the new "headers" from sliding around as you scroll, you need to set the properties (not attributes) [frozenColumn](https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid.frozenColumn) and [frozenRow](https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid.frozenRow)

5. Attach to the event [beginfreezemove](https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid#event:beginfreezemove) and call `e.preventDefault();` to prevent the user from moving the freeze marker.

So yes, you can do it, but it would take some effort and the result will be something akin to Frankenstein's monster, but should work as desired.

Even though I'm biased towards having people use this component over other grid components, you might have an easier go of it using a competing product that natively supports the behavior you're describing.  I will add it in V2, which is most likely more than one year away.

How would you describe this schema/data?  Or would you say is it defined more through invoking methods?  I would love to hear your ideal way of passing this behavior in so I can add it or something like it.

**Comment by vasu-vvp** [comment]
Hi, Thank you!
Sorry for late response. 
I will post my idea in detail in next 2-3 days.

**Comment by TonyGermaneri** [comment]
That's great!  I'll post it in the tutorials if you get something good going.  Good luck!

**Comment by TonyGermaneri** [comment]
I'm closing this ticket due to inactivity.  Doesn't seem to be useful to be open anyhow.  If you ever get anything going with your idea please let me know, I'll post it in the documentation.

**Comment by gmareater** [comment]
so bad,it could be very great feature

**Comment by appu-sm** [comment]
Still this feature is not included?

**Comment by ndrsn** [comment]
It is not, but if you would like to contribute a solution in the form of a pull request, we'd be happy to look at it!
