### ISSUE TITLE
Not really an issue...but a question

### ISSUE THREAD

**Issue by Stefdv** [TonyGermaneri/canvas-datagrid#65]
I would like to have a checkbox in a cell ( type: 'boolean' ), now i understand that we are dealing with a canvas and i can't just put html in it...
So i guess i need to place an image of a checkbox in the cell and then when i click on it ...change the image to a checked-checkbox image ?

Any thoughts on that ?

**Comment by TonyGermaneri** [comment]
You can indeed just put HTML in it!  Responding to the click event and modifying the HTML is your responsibility because it will be a picture of the HTML, the the actual HTML.

https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid.cell.innerHTML

https://tonygermaneri.github.io/canvas-datagrid/docs/#tutorial--Draw-HTML-via-Event

Hope that answers your question.

**Comment by TonyGermaneri** [comment]
Just tried it, it seems the SVG rendering subsystem is very strict.  If you run into the same problem I did, you'll notice it throwing an error when using `<input type="checkbox">`.  It seems it needs a closing tag.  Below is a working example:

    var grid = canvasDatagrid({
        parentNode: parentNode,
        data: [
            {col1: 'foo', col2: 0, col3: 'a'},
            {col1: 'bar', col2: 1, col3: 'b'},
            {col1: 'baz', col2: 2, col3: 'c'}
        ]
    });
    grid.addEventListener('afterrendercell', function (e) {
        if (e.cell.columnIndex === 1 && e.cell.rowIndex > -1) {
            e.cell.innerHTML = '<input type="checkbox"></input>';
        }
    });
    grid.draw();

**Comment by Stefdv** [comment]
tx...i'll give it a try
