### ISSUE TITLE
Scale of canvas is wrong when table is empty on HiDPI monitor

### ISSUE THREAD

**Issue by luveti** [TonyGermaneri/canvas-datagrid#72]
This is happening with the latest dist file on both a 2016 MacBook Pro 15" Retina display, and a 4K display.

Here's the table with data:

![image](https://user-images.githubusercontent.com/4952718/33721721-d62cc59c-db35-11e7-82f5-a08e462ae286.png)

And here it is without data:

![image](https://user-images.githubusercontent.com/4952718/33721747-e722c518-db35-11e7-9fcb-4bad65a8320b.png)

This should reproduce the issue:
```html
<html>
	<head>
		<script src="canvas-datagrid.min.js"></script>
		<script>
			window.onload = () => {
				const grid = canvasDatagrid({
					editable:          false,
					parentNode:        document.body,
					schema:            [{name: "name"}],
					showColumnHeaders: false,
					showRowHeaders:    false,
				})

				window.grid = grid

				grid.setColumnWidth(0, 600)
				grid.style.cellHeight = 125

				const data = []
				for (let i = 0; i < 100; i++) data.push({ name: `Test ${i}` })
				grid.data = data
			}
		</script>
	</head>
	<body></body>
</html>
```

**Comment by TonyGermaneri** [comment]
Thanks for reproducing the issue.  I've seen it before, but I didn't connect it to an empty record set.  I'll try and get it fixed asap.  

There's another related issue that is even more difficult to fix, which is when a user moves their window from a low DPI display to a high DPI display there is no event that indicates that occurs.  Running draw again is sufficient to fix the issue, but running draw over and over without cause hardly seems like a solution.

**Comment by luveti** [comment]
A simple interval that checks for changes to `window.devicePixelRatio` and redraws would probably suffice. I would probably put it behind a setting users can opt into since setInterval isn't necessarily cpu friendly.

```js
function ondpichange(handler, pollRate) {
	var oldValue = window.devicePixelRatio
	return window.setInterval(function() {
		var newValue = window.devicePixelRatio
		if (newValue != oldValue) handler(oldValue, newValue)
		oldValue = newValue
	}, pollRate || 100)
}
```

**Comment by TonyGermaneri** [comment]
So, I guess the problem was the order in which things were being called.  Because `self.canvas.width = self.width * ratio` could be called before `self.ctx.scale(ratio, ratio);` things could go wrong.  I moved the assignments to the draw loop to prevent any race conditions.  The immediate bug is fixed.

This introduced a serious performance problem on retina displays.  I need to profile and see what slows it down, but I suspect it is the low level canvas draw methods.  Makes sense if you consider it doubled the resolution of the canvas where before it was not properly doing that.  If that is indeed the case, it would appear I will need to add a `maxPixelRatio` attribute to allow the capping of the resolution.

The perception of ratio change as you move from screen to screen isn't as profound and I expected it to be.  You can see it change, but it looks like a "de-resing" and not the drastic resizing of the whole grid that I thought would occur.

**Comment by TonyGermaneri** [comment]
Thanks again for finding the bug and reporting it.  It's really a great help to have other people using it so I can work out all the bugs.

**Comment by stevewillard** [comment]
I noticed that when going from `0.18.23` from `0.18.20`, this rescaling issue goes away, but overall the grid looks a bit blurry on my Macbook Pro in Chrome. If it helps, I can try to put together a reproducible example.

**Comment by TonyGermaneri** [comment]
Wow, 0.18.23 already, I'm impressed!  I've added [maxPixelRatio](https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid.args.maxPixelRatio) and set the default to 1.5 to try and reach a compromise on quality vs. performance as a stop gap solution to the performance problem.  To see the full resolution on the macbook set that value to 2 or higher.

I've had to change my workstation setup a bit to deal with this bug.  Now my macbook is open and on a desk next to my 3 monitors that I typically use with the laptop closed and tucked behind them.  Just so you know I'm testing on the same hardware.

The real problem is that the draw loop is so unperformant.  I've done a lot of profiling on the loop and discovered a majority of the draw time is spent drawing text.  

Because the text is completely redrawn on each frame there are a few optimizations that I can create to improve the draw loops performance.  The first is to cache the text in each cell in an in memory canvas the first time I see the text/color combo, then put it in a hashmap where the value is the rect of the text on the in the memory canvas.  That will greatly enhance the performance of the draw loop at the cost of increasing the overall complexity of the function.

The next step is to detect if the frame really needs to be drawn.  Currently I am very wasteful in that process redrawing every single mouse pixel movement (or any other event) which can suck up tons of cycles for no reason (hear that fan turn on?).  This is _far_ more difficult and will most likely create more than one regression.  Hopefully the first performance measure will solve the problem enough that I won't have to implement the second, which I probably should anyway.

**Comment by stevewillard** [comment]
Ah, that makes sense. I think that sounds like a reasonable approach to improving the performance.

I fiddled with the `maxPixelRatio` a bit, and I found `2` to be totally fine for my use case, but it's good to know I can tweak this. Thanks!
