### ISSUE TITLE
[Feature request] set sort column / direction through API

### ISSUE THREAD

**Issue by stevewillard** [TonyGermaneri/canvas-datagrid#75]
I'm interested in sorting on the server, instead of the client.

It would be helpful, if it was possible to specify a `sortDirection` as part of the header/schema for the data. In other words, I would like to render the datagrid, and initially have a column sorted with a 'down arrow', but not actually let the grid do the sorting. I tried a few different ways to capture the click event for the header and do something like this:
```
this.grid.orderBy = value;
this.grid.orderDirection = 'asc';
this.grid.dispatchEvent('ordercolumn', { name: value, direction: 'asc' });
this.grid.draw();
```
But that didn't seem to work.

I understand if you feel like this is outside the scope of your library - if so, please go ahead and close this. Again, this library is great; thanks again!

**Comment by TonyGermaneri** [comment]
Totally in scope.  I think there's a way to do it without any changes to the lib, just nothing simple.  It would inevitably involve attaching to and preventing the defaults of certain click events, and maybe drawing your own order by arrow.  This is a non-optimal solution so I'll have to implement something to make it easier.

**Comment by TonyGermaneri** [comment]
I've added this feature to v0.18.30.

To achieve the behavior you're looking for do the following:

* Add an event listener preventing the default sort behavior

    grid.addEventListener('beforesortcolumn', function (e) {
        e.preventDefault();
    });

* As you suggested select the column and direction via properties on the grid.

    grid.orderBy = 'S';
    grid.orderDirection = 'desc';

Because the event listener `beforesortcolumn` is present and preventing the default behavior of sorting the list the getter/setters `orderBy` and `orderDirection` do nothing _but_ update the internal `orderBy` and `orderDirection` causing the arrow to be drawn over the respective column.  You will need to call `draw()` after the change or wait for the user's mouse movements to do that for you.  

Might I suggest you indicate a wait state by changing the `grid.style.cursor` to something like `progress` until the async event has completed?

Let me know if it works out for you, then I'll move the ticket into the completed column.

**Comment by stevewillard** [comment]
These changes worked great! Feel free to close out this issue. Thanks for tackling this so quickly.
