### ISSUE TITLE
Does it make sense to push dist/*.map files to repository?

### ISSUE THREAD

**Issue by tryshchenko** [TonyGermaneri/canvas-datagrid#85]
### Expected behavior and actual behavior.
Temporary development files shouldn't be pushed

### Steps to reproduce the problem.
Look at the repository

### Specifications like the version of the project, operating system, or hardware.

__

**Comment by tryshchenko** [comment]
Proposed improvement https://github.com/TonyGermaneri/canvas-datagrid/pull/86

**Comment by TonyGermaneri** [comment]
Until the program is v1 I'd like to keep the .map files there.  I use them an embarrassingly large number of times in production systems. :(

After v1 I'm open to removing them.

I'd like to find a way to remove the entire /dist directory for all the problems it causes me.

I'll keep your ticket open as a reminder to remove it post v1.

**Comment by TonyGermaneri** [comment]
I think once this is done, the desired way to fix the problem will be to not create the .map file in the first place for the production output.

If you want to create a PR that alters `package.json` so the production version does not create a .map file I'll merge it after V1 is released.  Or just wait for me to do it after V1, I'll leave this ticket open to remind me.

I'll always want to keep the map file for the debug version so I'm going to close your PR.

**Comment by ndrsn** [comment]
We've solved this by ignoring map files in the repository, but building and including them in the package distribution upon release.

**Comment by jswolf19** [comment]
In the npm package up until 0.22.17, canvas-datagrid.map was included, but from there it does not seem to be... canvas-datagrid.debug.map and (from 2.5.1) canvas-datagrid.module.js.map are there. Was there a reason for this change?

**Comment by ndrsn** [comment]
Do you mean that `canvas-datagrid.js` does not have a corresponding map file, whereas the `.debug.js` and `.module.js` files _do_? I *think* the reasoning was along the lines that only `debug` needs a map, file, as you wouldn't want one in production. The ESM version is produced by Rollup, and I think I missed that it produces a sourcemap when I merged the PR. It's inconsistent, for sure.

Do you have a preference, and if so, why?

**Comment by jswolf19** [comment]
While in the general sense, having a map file only for the debug version should be all that's necessary, I don't really see much reason not to include it, either. If you don't want it in production, then don't put it in production. I could also imagine some (albeit extremely rare) cases where the debug code might work differently than the non-debug code. Just looking at the first part, === is changed to ==, for example. I do find it more convenient, though, as well, to use the same source as much as possible in development and release, so rather than adding some logic at some step to use the `.js` or the `.debug.js`, I personally would like to use the `.js` and be able to debug with it when necessary. Not to mention that it eases debugging in production, when you have to do that.

The only minor hitch is that you might still get unwanted requests for the map file if someone has developer tools open in the browser, or if there's a browser that gets map files even when developer tools isn't open, but that's the only argument against it that I can think of at the moment...

I'm also not a heavy JavaScript coder, though, so there may be other good reasons that I don't know about, and I also don't know what the general consensus is in the JavaScript world, so my opinions may not reflect those of the average consumer ^_~
