### ISSUE TITLE
Per cell-specific styling and Formatting

### ISSUE THREAD

**Issue by AviAkGlobal** [TonyGermaneri/canvas-datagrid#99]
I would like to add a feature - per-cell styling and formatting. 
I didn't see any way of doing so with the current library version.

**Comment by TonyGermaneri** [comment]
This should do what you're asking for:

https://tonygermaneri.github.io/canvas-datagrid/docs/index.html#tutorial--Conditionally-set-colors

There are some things it cannot do, but as features as requested I can add them.

The above suggestion uses the fast pure canvas method.  There is another method using HTML (really SVG parsing HTML in a limited way):

https://tonygermaneri.github.io/canvas-datagrid/docs/index.html#tutorial--Draw-HTML-via-Event

This is slower because it involves taking pictures of SVG inserted into offscreen canvas elements.  It's also a limited subset of HTML, but you do get access to CSS there.

Either of these methods can provide limited formatting on a per cell basis.

You can also abort the drawing of the cell all together and draw your own thing in the cell, but I suspect you don't want to do that:

https://tonygermaneri.github.io/canvas-datagrid/docs/index.html#tutorial--Draw-a-picture

**Comment by AviAkGlobal** [comment]
I eventually prepared a 'style-processing matrix', which keeps the style per cell and sets it during:
`function drawCell(d, rowOrderIndex, rowIndex)`

I'm not sure it's better than using event listener, but it works. Also, using this approach prevents the canvas from drawing something once and than draw something else after the event has been caught.

**Comment by TonyGermaneri** [comment]
I'm glad you figured out a way to do it.  I'd love to see what you came up with.

> Also, using this approach prevents the canvas from drawing something once and than draw something else after the event has been caught.

For most events you can use e.preventDefault() to stop it from drawing.
